swagger: "2.0"
info:
  description: "This is a test RestAPI microservice, done in Go."
  version: "1.0.0"
  title: "go-test-class-api"
  contact:
    email: "alexgrauroca91@gmail.com"
host: "localhost:5050"
basePath: "/api/v1"
tags:
- name: "booking"
  description: "Operations abount bookings"
- name: "class"
  description: "Operations about classes"
schemes:
- "http"
paths:
  /bookings:
    post:
      tags:
      - "booking"
      summary: "Add a new booking"
      operationId: "addBooking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Booking object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/CreateBooking"
      responses:
        "201":
          description: "Created booking"
          schema:
            $ref: "#/definitions/Booking"
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error"
  /classes:
    get:
      tags:
      - "class"
      summary: "Get a list of existing classes"
      operationId: "getClasses"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Classes found"
          schema:
            type: "object"
            properties:
              classes:
                type: array
                items:
                  $ref: "#/definitions/Class"
        "404":
          description: "Classes not found"
        "500":
          description: "Internal server error"
    post:
      tags:
      - "class"
      summary: "Add a new class"
      operationId: "addClass"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Class object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/CreateClass"
      responses:
        "201":
          description: "Created class"
          schema:
            $ref: "#/definitions/Class"
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error"
definitions:
  Booking:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      date:
        type: "string"
        format: "date-time"
  Class:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      startDate:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"
      capacity:
        type: "integer"
        format: "int64"
  CreateBooking:
    type: "object"
    properties:
      name:
        type: "string"
      date:
        type: "string"
        format: "date-time"
  CreateClass:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      startDate:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"
      capacity:
        type: "integer"
        format: "int64"
